name: Publish Docker image

on:
  push:
    branches: 
      - main
    tags:
      - 'v*'

env:
  DOCKER_NAME: "vincentking/aurora"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: get_image_name
        run: |
          VERSION=latest

          IMAGE_NAME=${{ env.DOCKER_NAME }}:$VERSION

          echo IMAGE_NAME=$IMAGE_NAME

          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract branch or tag name
        id: ref
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "::set-output name=version::${GITHUB_REF#refs/tags/}"
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            echo "::set-output name=version::${GITHUB_REF#refs/heads/}"
          else
            echo "::set-output name=version::latest"
          fi
        
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          # platforms: |
          #   linux/amd64
          tags: ${{ env.DOCKER_NAME }}:${{ steps.ref.outputs.version }}
